name: base
channels:
  - defaults
  - conda-forge
dependencies:
  - python=39
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - jupyter
  - pip:
    - tensorflow
    - torch
    - transformers
    - pytest
    - flake8
